<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>09302d0a-e8c4-4d3b-8ab6-834b686fddcc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartProd.Server\SmartProd.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.1.0" />
  </ItemGroup>
</Project>
